development:
  bucket: <%= bucket %>
  access_key_id: <%= access_key_id %>
  secret_access_key: <%= secret_access_key %>

test:
  bucket: <%= bucket %>
  access_key_id: <%= access_key_id %>
  secret_access_key: <%= secret_access_key %>

production:
  bucket: <%= bucket %>
  access_key_id: <%= access_key_id %>
  secret_access_key: <%= secret_access_key %>

